= Renarde image:renarde-head.svg[width=25em] Web Framework - Getting Started
:favicon: _images/renarde-head.svg

include::./includes/attributes.adoc[]
:config-file: application.properties

[.float-group]
--
image::renarde.svg[alt=Renarde,width=100,float="right"]

Renarde image:renarde-head.svg[width=15em] is a server-side Web Framework based on Quarkus, {quarkus-guides-url}/qute-reference[Qute],
{quarkus-guides-url}/hibernate-orm-panache[Hibernate] and {quarkus-guides-url}/rest[Quarkus REST].


[source,xml,subs=attributes+]
----
<dependency>
  <groupId>io.quarkiverse.renarde</groupId>
  <artifactId>quarkus-renarde</artifactId>
  <version>{quarkus-renarde-version}</version>
</dependency>
----
--

== First: an example

Let's see how you can quickly build a Web Application with Renarde. Let's start with a _Controller_:

[source,java]
----
package rest;

import jakarta.ws.rs.Path;

import io.quarkus.qute.CheckedTemplate;
import io.quarkus.qute.TemplateInstance;
import io.quarkiverse.renarde.Controller;

public class Application extends Controller {

    @CheckedTemplate
    static class Templates {
        public static native TemplateInstance index();
    }

    @Path("/")
    public TemplateInstance index() {
        return Templates.index();
    }
}
----

A _Controller_ is the logic class that binds URIs to actions and views. They are almost like regular
{quarkus-guides-url}/resteasy-reactive#declaring-endpoints-uri-mapping[JAX-RS endpoints],
but you opt-in to special magic by extending the `Controller` class, which gives you nice methods,
but also super friendly behaviour.

In this Controller we declare a Qute template, and map the `/` to it.

We can then define the main page in `src/main/resources/templates/Application/index.html`:

[source,html]
----
<!DOCTYPE html>
<html lang="en">
  <body>
    Hello, World!
  </body>
</html>
----

Now if you navigate to your application at http://localhost:8080 you will see `Hello, World!` rendered.
